export const MAKE_USER_UPDATE_REQUEST = 'MAKE_USER_UPDATE_REQUEST';
export const MAKE_USER_UPDATE_SUCCESS = 'MAKE_USER_UPDATE_SUCCESS';
export const MAKE_USER_UPDATE_FAILURE = 'MAKE_USER_UPDATE_FAILURE';
export const GET_USER_ID_UPADTE = 'GET_USER_ID_UPADTE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
